// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-smart-links.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.96.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/site.ts
var SITE_ORIGIN = "https://cloud-publish-pro.lovable.app";

// src/lib/mcp/tools/list-smart-links.ts
var list_smart_links_default = defineTool({
  name: "list_smart_links",
  title: "List smart links",
  description: "List the signed-in user's smart links with their slug, destination, short URL and click count.",
  inputSchema: {
    search: z.string().trim().optional().describe("Optional text filter on slug, title or destination."),
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum number of links to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("user_smart_links").select("id, slug, title, description, destination_url, clicks, metadata, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (search) {
      query = query.or(
        `slug.ilike.%${search}%,title.ilike.%${search}%,destination_url.ilike.%${search}%`
      );
    }
    const { data, error } = await query;
    if (error) throw new ToolError(error.message);
    const links = (data ?? []).map((row) => ({
      id: row.id,
      slug: row.slug,
      title: row.title,
      description: row.description,
      destinationUrl: row.destination_url,
      shortUrl: `${SITE_ORIGIN}/s/${row.slug}`,
      clicks: row.clicks,
      gated: Boolean(row.metadata && Object.keys(row.metadata).length > 0),
      createdAt: row.created_at
    }));
    return {
      content: [
        {
          type: "text",
          text: links.length ? links.map((l) => `${l.shortUrl} -> ${l.destinationUrl} (${l.clicks} clicks)${l.gated ? " [gated]" : ""}`).join("\n") : "No smart links yet."
        }
      ],
      structuredContent: { links, count: links.length }
    };
  }
});

// src/lib/mcp/tools/create-smart-link.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
function normalizeSlug(input) {
  return input.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40);
}
function randomSlug() {
  const alphabet = "abcdefghijkmnpqrstuvwxyz23456789";
  let out = "";
  const bytes = crypto.getRandomValues(new Uint8Array(7));
  for (const b of bytes) out += alphabet[b % alphabet.length];
  return out;
}
var create_smart_link_default = defineTool2({
  name: "create_smart_link",
  title: "Create smart link",
  description: "Create a short smart link for the signed-in user, optionally gated behind a YouTube action before the destination unlocks.",
  inputSchema: {
    destinationUrl: z2.string().url().describe("Where the visitor lands after unlocking."),
    title: z2.string().trim().max(120).optional().describe("Title shown on the unlock page."),
    description: z2.string().trim().max(400).optional().describe("Short description shown on the unlock page."),
    slug: z2.string().trim().max(40).optional().describe("Custom slug; auto-generated when omitted."),
    youtubeVideoId: z2.string().trim().optional().describe("YouTube video ID to require watching before the link unlocks."),
    youtubeChannelId: z2.string().trim().optional().describe("YouTube channel ID to require subscribing to before the link unlocks.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const slug = input.slug ? normalizeSlug(input.slug) : randomSlug();
    if (!slug) throw new ToolError2("Slug must contain at least one letter or number.");
    const metadata = {};
    if (input.youtubeVideoId) metadata.youtubeVideoId = input.youtubeVideoId;
    if (input.youtubeChannelId) metadata.youtubeChannelId = input.youtubeChannelId;
    if (Object.keys(metadata).length) metadata.requireWatch = true;
    const { data, error } = await supabase.from("user_smart_links").insert({
      user_id: ctx.getUserId(),
      slug,
      title: input.title ?? null,
      description: input.description ?? null,
      destination_url: input.destinationUrl,
      metadata
    }).select("id, slug, destination_url, clicks").single();
    if (error) {
      throw new ToolError2(
        error.code === "23505" ? `The slug "${slug}" is already taken.` : error.message
      );
    }
    const shortUrl = `${SITE_ORIGIN}/s/${data.slug}`;
    return {
      content: [{ type: "text", text: `Created ${shortUrl} -> ${data.destination_url}` }],
      structuredContent: { id: data.id, slug: data.slug, shortUrl, destinationUrl: data.destination_url }
    };
  }
});

// src/lib/mcp/tools/get-link-analytics.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var get_link_analytics_default = defineTool3({
  name: "get_link_analytics",
  title: "Get link analytics",
  description: "Summarize click performance across the signed-in user's smart links, with a ranked list of top performers.",
  inputSchema: {
    top: z3.number().int().min(1).max(25).default(5).describe("How many top links to include.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ top }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_smart_links").select("slug, title, destination_url, clicks, metadata").order("clicks", { ascending: false });
    if (error) throw new ToolError3(error.message);
    const rows = data ?? [];
    const totalClicks = rows.reduce((sum, r) => sum + (r.clicks ?? 0), 0);
    const gated = rows.filter(
      (r) => r.metadata && Object.keys(r.metadata).length > 0
    ).length;
    const topLinks = rows.slice(0, top ?? 5).map((r) => ({
      slug: r.slug,
      title: r.title,
      shortUrl: `${SITE_ORIGIN}/s/${r.slug}`,
      destinationUrl: r.destination_url,
      clicks: r.clicks
    }));
    const summary = [
      `Links: ${rows.length}`,
      `Total clicks: ${totalClicks}`,
      `Gated links: ${gated}`,
      "",
      ...topLinks.map((l, i) => `${i + 1}. ${l.shortUrl} \u2014 ${l.clicks} clicks`)
    ].join("\n");
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: { totalLinks: rows.length, totalClicks, gatedLinks: gated, topLinks }
    };
  }
});

// src/lib/mcp/tools/delete-smart-link.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var delete_smart_link_default = defineTool4({
  name: "delete_smart_link",
  title: "Delete smart link",
  description: "Permanently delete one of the signed-in user's smart links by its slug.",
  inputSchema: {
    slug: z4.string().trim().min(1).describe("Slug of the smart link to delete.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_smart_links").delete().eq("slug", slug).select("slug");
    if (error) throw new ToolError4(error.message);
    if (!data || data.length === 0) throw new ToolError4(`No smart link found with slug "${slug}".`);
    return {
      content: [{ type: "text", text: `Deleted smart link "${slug}".` }],
      structuredContent: { slug, deleted: true }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "efsricqctygfcmcocvnp";
var mcp_default = defineMcp({
  name: "remix-of-remix-of-remix-of-remix-of-remix-of-social-sync-hub",
  title: "Remix of Remix of Remix of Remix of Remix of Social Sync Hub",
  version: "0.1.0",
  instructions: "Tools for managing Creator Cloud smart links. Use `list_smart_links` to browse the signed-in user's links, `create_smart_link` to make a new short link (optionally gated behind a YouTube watch/subscribe action), `get_link_analytics` for click performance, and `delete_smart_link` to remove one.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_smart_links_default, create_smart_link_default, get_link_analytics_default, delete_smart_link_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
